//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispatch
    {
        public int id_cars { get; set; }
        public System.DateTime dispatch1 { get; set; }
        public int id_dispatch { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
