//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dogovor
    {
        public int id_dogovor { get; set; }
        public int id_client { get; set; }
        public int id_cars { get; set; }
        public int id_issue { get; set; }
        public int id_refund { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Client Client { get; set; }
        public virtual Issue Issue { get; set; }
        public virtual Refund Refund { get; set; }
    }
}
